baseURL = 'https://belluscio-abafr.github.io/galleria-corsi/'
languageCode = 'it'
title = "Galleria dei corsi dell'Accademia di Belle Arti di Frosinone"
theme = 'abafr-tmp'

# Disabilita la generazione delle pagine di tassonomie (categorie e tag)
disableKinds = ["taxonomy", "term"]

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[params]
  description = "Galleria dei migliori progetti di tesi e di corso di media art degli studenti dell'Accademia di Belle Arti di Frosinone"
  institution = "Accademia di Belle Arti di Frosinone"
  institutionUrl = "https://www.accademiabellearti.fr.it/"

[menu]
  [[menu.main]]
    name = "Presentazione"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Progetti"
    url = "/progetti/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
